contentType:
  name: Content-Type
  in: header
  required: false
  description: Media type van het request.
  schema:
    type: string
contentCrs:
  name: Content-Crs
  in: header
  required: false
  description: CRS van de meegegeven geometrie.
  schema:
    type: string
    enum:
      - 'epsg:4258'
      - 'epsg:28992'
    default: 'epsg:4258'
acceptCrs:
  name: Accept-Crs
  in: header
  required: false
  description: Gewenste CRS van de coördinaten in de response.
  schema:
    type: string
    enum:
      - 'epsg:4258'
      - 'epsg:28992'
    default: 'epsg:4258'
